# Generated by Django 4.2.2 on 2023-06-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccionPais', models.CharField(max_length=300)),
                ('direccionProvincia', models.CharField(max_length=300)),
                ('direccionCiudad', models.CharField(max_length=300)),
                ('direccionCallle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleadoNombre', models.CharField(max_length=500)),
                ('empleadoApellido', models.CharField(max_length=500)),
                ('empleadoEdad', models.CharField(max_length=3)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dirección', to='modelo.direccion')),
            ],
        ),
    ]
